use_frameworks!

platform :ios, '9.0'

target 'ZCMemoTools_Example' do
  pod 'ZCMemoTools', :path => '../'

  target 'ZCMemoTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
